from geoalchemy2 import alembic_helpers

import app.models  # noqa: F401  (registers tables)
from alembic import context
from app.db.session import Base, engine

target_metadata = Base.metadata

# PostGIS-owned tables that must never be autogenerated/dropped.
_IGNORED_TABLES = {"spatial_ref_sys", "layer", "topology"}


def include_object(obj, name, type_, reflected, compare_to):
    if type_ == "table" and (name in _IGNORED_TABLES or (reflected and compare_to is None)):
        # Never touch tables this app doesn't own (PostGIS tiger/topology schemas etc.).
        return False
    return alembic_helpers.include_object(obj, name, type_, reflected, compare_to)


def run_migrations_online() -> None:
    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            process_revision_directives=alembic_helpers.writer,
            render_item=alembic_helpers.render_item,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


run_migrations_online()
