"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 11:55:20.675987
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE SEQUENCE IF NOT EXISTS thermal_event_public_seq START 1000")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_api_cache_expires_at'), 'api_cache', ['expires_at'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('homepage', sa.Text(), nullable=False),
    sa.Column('license', sa.Text(), nullable=False),
    sa.Column('access', sa.String(length=24), nullable=False),
    sa.Column('cadence', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_record_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_total', sa.BigInteger(), nullable=False),
    sa.Column('requests_total', sa.BigInteger(), nullable=False),
    sa.Column('requests_failed', sa.BigInteger(), nullable=False),
    sa.Column('latency_ms_ewma', sa.Float(), nullable=True),
    sa.Column('dataset_version', sa.String(length=120), nullable=True),
    sa.Column('dataset_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('facility_type', sa.String(length=32), nullable=False),
    sa.Column('subtype', sa.String(length=80), nullable=True),
    sa.Column('operator', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('capacity_value', sa.Float(), nullable=True),
    sa.Column('capacity_unit', sa.String(length=24), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('geom', Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('footprint', Geography(srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('primary_source', sa.String(length=32), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('ix_facilities_geom', 'facilities', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_facilities_type', 'facilities', ['facility_type'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'run_after', 'priority'], unique=False)
    op.create_index('uq_jobs_dedupe_active', 'jobs', ['dedupe_key'], unique=True, postgresql_where=sa.text("status IN ('queued','running') AND dedupe_key IS NOT NULL"))
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('feature_names', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('classes', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('training_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('label_provenance', sa.Text(), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('system_health',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('component', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_health_component'), 'system_health', ['component'], unique=False)
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=120), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('jobs_done', sa.Integer(), nullable=False),
    sa.Column('is_scheduler', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('facility_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_a', sa.UUID(), nullable=False),
    sa.Column('facility_b', sa.UUID(), nullable=False),
    sa.Column('relation', sa.String(length=24), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_a'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_b'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_a', 'facility_b', 'relation', name='uq_facility_relationship')
    )
    op.create_table('facility_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('source_type', sa.String(length=120), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('dataset_version', sa.String(length=80), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_facility_source_external')
    )
    op.create_index(op.f('ix_facility_sources_facility_id'), 'facility_sources', ['facility_id'], unique=False)
    op.create_table('ingestion_checkpoints',
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('dataset', sa.String(length=80), nullable=False),
    sa.Column('last_acq_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'dataset')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('dataset', sa.String(length=80), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_duplicate', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_runs_source_started', 'ingestion_runs', ['source_id', 'started_at'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('permission', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['permission'], ['permissions.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role'], ['roles.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role', 'permission')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('email = lower(email)', name='ck_users_email_lower'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role'], ['roles.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('ingestion_errors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_errors_run_id'), 'ingestion_errors', ['run_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_geospatial_table('saved_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('geom', Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('zoom', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('thermal_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=24), nullable=False),
    sa.Column('geom', Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('footprint', Geography(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('first_detected', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_detected', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('sensor_count', sa.Integer(), nullable=False),
    sa.Column('sensors', postgresql.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('datasets', postgresql.ARRAY(sa.String(length=48)), nullable=False),
    sa.Column('days_active', sa.Integer(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('frp_max', sa.Float(), nullable=True),
    sa.Column('frp_mean', sa.Float(), nullable=True),
    sa.Column('frp_sum', sa.Float(), nullable=True),
    sa.Column('frp_std', sa.Float(), nullable=True),
    sa.Column('confidence_mean', sa.Float(), nullable=True),
    sa.Column('night_fraction', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('review_status', sa.String(length=24), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('persistence_class', sa.String(length=16), nullable=True),
    sa.Column('persistence_score', sa.Float(), nullable=True),
    sa.Column('persistence_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('classification_probability', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_state', sa.String(length=32), nullable=True),
    sa.Column('confidence_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_quality', sa.String(length=16), nullable=True),
    sa.Column('data_quality_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fingerprint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nearest_facility_id', sa.UUID(), nullable=True),
    sa.Column('nearest_facility_distance_m', sa.Float(), nullable=True),
    sa.Column('admin_state', sa.String(length=120), nullable=True),
    sa.Column('admin_district', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('enrichment_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_mode IN ('live', 'historical', 'demo')", name='ck_event_data_mode'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nearest_facility_id'], ['facilities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_events_classification', 'thermal_events', ['classification'], unique=False)
    op.create_index('ix_events_confidence', 'thermal_events', ['confidence_score'], unique=False)
    op.create_geospatial_index('ix_events_geom', 'thermal_events', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_events_last_detected', 'thermal_events', ['last_detected'], unique=False)
    op.create_index('ix_events_persistence', 'thermal_events', ['persistence_class'], unique=False)
    op.create_index('ix_events_status', 'thermal_events', ['status', 'review_status'], unique=False)
    op.create_index(op.f('ix_thermal_events_admin_district'), 'thermal_events', ['admin_district'], unique=False)
    op.create_index(op.f('ix_thermal_events_admin_state'), 'thermal_events', ['admin_state'], unique=False)
    op.create_index(op.f('ix_thermal_events_nearest_facility_id'), 'thermal_events', ['nearest_facility_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('center', Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('radius_m', sa.Float(), nullable=True),
    sa.Column('watchlist_id', sa.UUID(), nullable=True),
    sa.Column('source_classes', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('persistence_classes', postgresql.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('facility_types', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('facility_within_m', sa.Float(), nullable=True),
    sa.Column('min_confidence', sa.Float(), nullable=True),
    sa.Column('min_frp', sa.Float(), nullable=True),
    sa.Column('min_duration_hours', sa.Float(), nullable=True),
    sa.Column('channels', postgresql.ARRAY(sa.String(length=12)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('source_class', sa.String(length=32), nullable=False),
    sa.Column('persistence_class', sa.String(length=16), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_state', sa.String(length=32), nullable=False),
    sa.Column('confidence_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_model_id', sa.String(length=64), nullable=False),
    sa.Column('supporting_model_ids', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_model_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classifications_event_current', 'classifications', ['event_id', 'is_current'], unique=False)
    op.create_table('event_facility_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('bearing_deg', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('attribution_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'facility_id', name='uq_event_facility')
    )
    op.create_index(op.f('ix_event_facility_links_event_id'), 'event_facility_links', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_facility_links_facility_id'), 'event_facility_links', ['facility_id'], unique=False)
    op.create_table('investigation_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_notes_event_id'), 'investigation_notes', ['event_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('opened_by', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_investigation_event')
    )
    op.create_table('land_context',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('osm_type', sa.String(length=10), nullable=False),
    sa.Column('osm_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'osm_type', 'osm_id', name='uq_land_context_feature')
    )
    op.create_index(op.f('ix_land_context_event_id'), 'land_context', ['event_id'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.String(length=64), nullable=False),
    sa.Column('prediction', sa.String(length=32), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('probabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('features_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_event_created', 'model_predictions', ['event_id', 'created_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_event_id'), 'reports', ['event_id'], unique=False)
    op.create_table('satellite_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('collection', sa.String(length=60), nullable=False),
    sa.Column('item_id', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('processing_level', sa.String(length=20), nullable=True),
    sa.Column('relation', sa.String(length=12), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('item_url', sa.Text(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'provider', 'item_id', name='uq_satellite_event_item')
    )
    op.create_index(op.f('ix_satellite_observations_acquired_at'), 'satellite_observations', ['acquired_at'], unique=False)
    op.create_index(op.f('ix_satellite_observations_event_id'), 'satellite_observations', ['event_id'], unique=False)
    op.create_geospatial_table('thermal_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('geom', Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('acq_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acq_date', sa.Date(), nullable=False),
    sa.Column('acq_time', sa.String(length=4), nullable=False),
    sa.Column('sensor', sa.String(length=16), nullable=False),
    sa.Column('satellite', sa.String(length=16), nullable=False),
    sa.Column('dataset', sa.String(length=48), nullable=False),
    sa.Column('confidence_raw', sa.String(length=16), nullable=True),
    sa.Column('confidence_pct', sa.Float(), nullable=True),
    sa.Column('frp', sa.Float(), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('brightness_2', sa.Float(), nullable=True),
    sa.Column('scan', sa.Float(), nullable=True),
    sa.Column('track', sa.Float(), nullable=True),
    sa.Column('daynight', sa.String(length=1), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_mode IN ('live', 'historical', 'demo')", name='ck_detection_data_mode'),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset', 'latitude', 'longitude', 'acq_datetime', name='uq_detection_natural_key')
    )
    op.create_geospatial_index('ix_detections_geom', 'thermal_detections', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_detections_unassigned', 'thermal_detections', ['acq_datetime'], unique=False, postgresql_where='event_id IS NULL')
    op.create_index(op.f('ix_thermal_detections_acq_datetime'), 'thermal_detections', ['acq_datetime'], unique=False)
    op.create_index(op.f('ix_thermal_detections_confidence_pct'), 'thermal_detections', ['confidence_pct'], unique=False)
    op.create_index(op.f('ix_thermal_detections_data_mode'), 'thermal_detections', ['data_mode'], unique=False)
    op.create_index(op.f('ix_thermal_detections_dataset'), 'thermal_detections', ['dataset'], unique=False)
    op.create_index(op.f('ix_thermal_detections_event_id'), 'thermal_detections', ['event_id'], unique=False)
    op.create_index(op.f('ix_thermal_detections_sensor'), 'thermal_detections', ['sensor'], unique=False)
    op.create_table('thermal_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('detection_count', sa.Integer(), nullable=False),
    sa.Column('frp_max', sa.Float(), nullable=True),
    sa.Column('frp_sum', sa.Float(), nullable=True),
    sa.Column('sensors', postgresql.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('night_count', sa.Integer(), nullable=False),
    sa.Column('first_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spread_m', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'obs_date', name='uq_observation_event_day')
    )
    op.create_index(op.f('ix_thermal_observations_event_id'), 'thermal_observations', ['event_id'], unique=False)
    op.create_geospatial_table('watchlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('geom', Geography(srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('radius_m', sa.Float(), nullable=True),
    sa.Column('admin_district', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('dataset', sa.String(length=60), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('pressure_hpa', sa.Float(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=80), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'kind', 'observed_at', name='uq_weather_event_kind_time')
    )
    op.create_index(op.f('ix_weather_observations_event_id'), 'weather_observations', ['event_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('reason', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'event_id', name='uq_alert_rule_event')
    )
    op.create_index(op.f('ix_alerts_event_id'), 'alerts', ['event_id'], unique=False)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    op.create_table('analyst_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('source_class', sa.String(length=32), nullable=True),
    sa.Column('persistence_class', sa.String(length=16), nullable=True),
    sa.Column('false_positive_reason', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('system_source_class', sa.String(length=32), nullable=True),
    sa.Column('system_confidence_score', sa.Float(), nullable=True),
    sa.Column('classification_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_reviews_event_id'), 'analyst_reviews', ['event_id'], unique=False)
    op.create_table('classification_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('classification_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('knowledge_type', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['thermal_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_evidence_classification_id'), 'classification_evidence', ['classification_id'], unique=False)
    op.create_index(op.f('ix_classification_evidence_event_id'), 'classification_evidence', ['event_id'], unique=False)
    op.create_table('report_exports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_exports_report_id'), 'report_exports', ['report_id'], unique=False)
    op.create_table('alert_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('recipient', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_deliveries_alert_id'), 'alert_deliveries', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_deliveries_alert_id'), table_name='alert_deliveries')
    op.drop_table('alert_deliveries')
    op.drop_index(op.f('ix_report_exports_report_id'), table_name='report_exports')
    op.drop_table('report_exports')
    op.drop_index(op.f('ix_classification_evidence_event_id'), table_name='classification_evidence')
    op.drop_index(op.f('ix_classification_evidence_classification_id'), table_name='classification_evidence')
    op.drop_table('classification_evidence')
    op.drop_index(op.f('ix_analyst_reviews_event_id'), table_name='analyst_reviews')
    op.drop_table('analyst_reviews')
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_event_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_weather_observations_event_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_geospatial_table('watchlist_items')
    op.drop_index(op.f('ix_thermal_observations_event_id'), table_name='thermal_observations')
    op.drop_table('thermal_observations')
    op.drop_index(op.f('ix_thermal_detections_sensor'), table_name='thermal_detections')
    op.drop_index(op.f('ix_thermal_detections_event_id'), table_name='thermal_detections')
    op.drop_index(op.f('ix_thermal_detections_dataset'), table_name='thermal_detections')
    op.drop_index(op.f('ix_thermal_detections_data_mode'), table_name='thermal_detections')
    op.drop_index(op.f('ix_thermal_detections_confidence_pct'), table_name='thermal_detections')
    op.drop_index(op.f('ix_thermal_detections_acq_datetime'), table_name='thermal_detections')
    op.drop_index('ix_detections_unassigned', table_name='thermal_detections', postgresql_where='event_id IS NULL')
    op.drop_geospatial_index('ix_detections_geom', table_name='thermal_detections', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('thermal_detections')
    op.drop_index(op.f('ix_satellite_observations_event_id'), table_name='satellite_observations')
    op.drop_index(op.f('ix_satellite_observations_acquired_at'), table_name='satellite_observations')
    op.drop_table('satellite_observations')
    op.drop_index(op.f('ix_reports_event_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_predictions_event_created', table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_land_context_event_id'), table_name='land_context')
    op.drop_table('land_context')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_investigation_notes_event_id'), table_name='investigation_notes')
    op.drop_table('investigation_notes')
    op.drop_index(op.f('ix_event_facility_links_facility_id'), table_name='event_facility_links')
    op.drop_index(op.f('ix_event_facility_links_event_id'), table_name='event_facility_links')
    op.drop_table('event_facility_links')
    op.drop_index('ix_classifications_event_current', table_name='classifications')
    op.drop_table('classifications')
    op.drop_geospatial_table('alert_rules')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_thermal_events_nearest_facility_id'), table_name='thermal_events')
    op.drop_index(op.f('ix_thermal_events_admin_state'), table_name='thermal_events')
    op.drop_index(op.f('ix_thermal_events_admin_district'), table_name='thermal_events')
    op.drop_index('ix_events_status', table_name='thermal_events')
    op.drop_index('ix_events_persistence', table_name='thermal_events')
    op.drop_index('ix_events_last_detected', table_name='thermal_events')
    op.drop_geospatial_index('ix_events_geom', table_name='thermal_events', postgresql_using='gist', column_name='geom')
    op.drop_index('ix_events_confidence', table_name='thermal_events')
    op.drop_index('ix_events_classification', table_name='thermal_events')
    op.drop_geospatial_table('thermal_events')
    op.drop_geospatial_table('saved_locations')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_ingestion_errors_run_id'), table_name='ingestion_errors')
    op.drop_table('ingestion_errors')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index('ix_ingestion_runs_source_started', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('ingestion_checkpoints')
    op.drop_index(op.f('ix_facility_sources_facility_id'), table_name='facility_sources')
    op.drop_table('facility_sources')
    op.drop_table('facility_relationships')
    op.drop_table('worker_heartbeats')
    op.drop_index(op.f('ix_system_health_component'), table_name='system_health')
    op.drop_table('system_health')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('organizations')
    op.drop_table('model_versions')
    op.drop_index('uq_jobs_dedupe_active', table_name='jobs', postgresql_where=sa.text("status IN ('queued','running') AND dedupe_key IS NOT NULL"))
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_facilities_type', table_name='facilities')
    op.drop_geospatial_index('ix_facilities_geom', table_name='facilities', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('facilities')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_api_cache_expires_at'), table_name='api_cache')
    op.drop_table('api_cache')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS thermal_event_public_seq")
