"""consolidation: priority, alert cooldown, facility sync tiles

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 15:55:48.254928
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_sync_tiles',
    sa.Column('tile_key', sa.String(length=24), nullable=False),
    sa.Column('west', sa.Float(), nullable=False),
    sa.Column('south', sa.Float(), nullable=False),
    sa.Column('east', sa.Float(), nullable=False),
    sa.Column('north', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('features_found', sa.Integer(), nullable=True),
    sa.Column('facilities_new', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tile_key')
    )
    op.create_index(op.f('ix_facility_sync_tiles_last_synced_at'), 'facility_sync_tiles', ['last_synced_at'], unique=False)
    op.add_column('alert_rules', sa.Column('cooldown_minutes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('alert_rules', sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('thermal_events', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('thermal_events', sa.Column('priority_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_thermal_events_priority_score'), 'thermal_events', ['priority_score'], unique=False)
    # Trigram indexes back server-side search (ILIKE '%term%') on names and admin areas.
    op.create_index('ix_facilities_name_trgm', 'facilities', ['name'], postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_events_district_trgm', 'thermal_events', ['admin_district'], postgresql_using='gin',
                    postgresql_ops={'admin_district': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_district_trgm', table_name='thermal_events')
    op.drop_index('ix_facilities_name_trgm', table_name='facilities')
    op.drop_index(op.f('ix_thermal_events_priority_score'), table_name='thermal_events')
    op.drop_column('thermal_events', 'priority_components')
    op.drop_column('thermal_events', 'priority_score')
    op.drop_column('alert_rules', 'last_notified_at')
    op.drop_column('alert_rules', 'cooldown_minutes')
    op.drop_index(op.f('ix_facility_sync_tiles_last_synced_at'), table_name='facility_sync_tiles')
    op.drop_table('facility_sync_tiles')
    # ### end Alembic commands ###
